# Generated by Django 5.2.6 on 2025-09-06 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('employee_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('branch_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], max_length=3)),
                ('university', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='api.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('publication_type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference')], max_length=10)),
                ('publication_date', models.DateField()),
                ('venue_name', models.CharField(max_length=200)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.professor')),
            ],
        ),
    ]
